<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-04-29T17:41:25 IST" name="Suite" finished-at="2020-04-29T17:41:55 IST" duration-ms="30283">
    <groups>
    </groups>
    <test started-at="2020-04-29T17:41:25 IST" name="VerifyHomeTitleTest" finished-at="2020-04-29T17:41:55 IST" duration-ms="30283">
      <class name="com.actitime.testscripts.VerifyHomeTitleTest">
        <test-method is-config="true" signature="classsetup()[pri:0, instance:com.actitime.testscripts.VerifyHomeTitleTest@14d3bc22]" started-at="2020-04-29T17:41:25 IST" name="classsetup" finished-at="2020-04-29T17:41:31 IST" duration-ms="6408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classsetup -->
        <test-method is-config="true" signature="loginSetup()[pri:0, instance:com.actitime.testscripts.VerifyHomeTitleTest@14d3bc22]" started-at="2020-04-29T17:41:31 IST" name="loginSetup" finished-at="2020-04-29T17:41:45 IST" duration-ms="13461" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSetup -->
        <test-method signature="verifyTitle()[pri:0, instance:com.actitime.testscripts.VerifyHomeTitleTest@14d3bc22]" started-at="2020-04-29T17:41:45 IST" name="verifyTitle" finished-at="2020-04-29T17:41:49 IST" duration-ms="4210" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.actitime.testscripts.VerifyHomeTitleTest.verifyTitle(VerifyHomeTitleTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.actitime.testscripts.VerifyHomeTitleTest@14d3bc22]" started-at="2020-04-29T17:41:49 IST" name="logout" finished-at="2020-04-29T17:41:54 IST" duration-ms="4880" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="exit()[pri:0, instance:com.actitime.testscripts.VerifyHomeTitleTest@14d3bc22]" started-at="2020-04-29T17:41:54 IST" name="exit" finished-at="2020-04-29T17:41:55 IST" duration-ms="1278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- com.actitime.testscripts.VerifyHomeTitleTest -->
    </test> <!-- VerifyHomeTitleTest -->
  </suite> <!-- Suite -->
</testng-results>
